### PR TITLE
fix: merge with TypeORM master [TECH-4623]

### PR DESCRIPTION
**Pull request by carlba**
Is merging the right approach here or would it better to graft the commit that adds our changes on the latest version of TypeORM?

### CODE REVIEW

**Comment by icercel** [comment]
my browser froze while trying to load 433 changed files
do we need to review all of them? :)

**Comment by carlba** [comment]
> my browser froze while trying to load 433 changed files do we need to review all of them? :)

Of course not this is just a merge of all the upstream TypeORM changes to this point. So only the changes I introduced in my previous commit which was the reason for the fork is intresting. But I do agree that it is very hard to see that in this diff. That is why I asked for alternate aproaches to this merge. Would it be better to simply create a new fork and the changes on top of that?

**Comment by carlba** [comment]
https://github.com/pocketsolutions/typeorm/commit/8342844b06ba7f39c9f5f881851acbf8ec030f7a

**Comment by elias-win** [comment]
> [8342844](https://github.com/pocketsolutions/typeorm/commit/8342844b06ba7f39c9f5f881851acbf8ec030f7a)

Are these the changes on top?

**Pull request closed without merging**
